language: node_js
node_js:
 - 10
before_script:
 - sudo apt update
 - sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
 - sudo chmod +x /usr/local/bin/docker-compose
 - sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
 - sudo apt-get install nodejs npm
 - sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
script:
 - printf "NEURALEGION_TOKEN=$NEURALEGION_TOKEN\nREPEATER=$REPEATER\n" > .env
 - cat .env
 - docker-compose --env-file=.env up -d
 - docker-compose config
 - printf "Start Nexploit Scan ðŸ"
 - >
  SCAN_ID=$(nexploit-cli scan:run
  --token $NEURALEGION_TOKEN
  --repeater $REPEATER
  --name "Test Travis Scan"
  --project $PROJECT_ID
  --crawler https://brokencrystals.com
  --smart)
 - printf "Scan was started with ID https://app.neuralegion.com/scans/$SCAN_ID\n"
 - printf "Wait for issues â³\n"
 - >
   (nexploit-cli scan:polling
   --interval 30s
   --timeout 20m
   --token $NEURALEGION_TOKEN
   --breakpoint medium_issue $SCAN_ID
allow_failure: true
after_script:
 - printf "Stop Scan ðŸ›‘"
 - nexploit-cli scan:stop 
 --token $NEURALEGION_TOKEN $SCAN_ID
